// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqXvHwSgtNEBpYlx7G1R7TcyBmR4u6Gvc',
    appId: '1:292910756994:web:0429ae802795036f95709b',
    messagingSenderId: '292910756994',
    projectId: 'tinder-for-movies-814ad',
    authDomain: 'tinder-for-movies-814ad.firebaseapp.com',
    storageBucket: 'tinder-for-movies-814ad.appspot.com',
    measurementId: 'G-CPHC74L4QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRYm0lPlPzt_YQBuzPlJnfWSl_uQQAqVg',
    appId: '1:292910756994:android:59b6263fb3a43dc095709b',
    messagingSenderId: '292910756994',
    projectId: 'tinder-for-movies-814ad',
    storageBucket: 'tinder-for-movies-814ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXOoLG_AE-z08v6xi_QELixPUZIS-SHKc',
    appId: '1:292910756994:ios:93f4d670f343ec5795709b',
    messagingSenderId: '292910756994',
    projectId: 'tinder-for-movies-814ad',
    storageBucket: 'tinder-for-movies-814ad.appspot.com',
    androidClientId: '292910756994-h7hd83r27hkhr2t2d0mcqbrc7letcf9m.apps.googleusercontent.com',
    iosClientId: '292910756994-m2mj61krlcich6mr26hml9fhrfhchi27.apps.googleusercontent.com',
    iosBundleId: 'dev.usuwana.myWatchlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXOoLG_AE-z08v6xi_QELixPUZIS-SHKc',
    appId: '1:292910756994:ios:5e24d5420870274695709b',
    messagingSenderId: '292910756994',
    projectId: 'tinder-for-movies-814ad',
    storageBucket: 'tinder-for-movies-814ad.appspot.com',
    androidClientId: '292910756994-h7hd83r27hkhr2t2d0mcqbrc7letcf9m.apps.googleusercontent.com',
    iosClientId: '292910756994-cv8sfde8b40i9d2q44907tla2vpj2qfb.apps.googleusercontent.com',
    iosBundleId: 'dev.usuwana.myWatchlist.RunnerTests',
  );
}
